### ISSUE TITLE
Remove grey line between navbar and HTML content in Firefox

### ISSUE THREAD

**Issue by hertz1** [oberon2007/vertex-theme#5]
There's a 1px line between navbar and HTML content that is pretty annoying on sites with a dark background. I don't know the purpose of this line, but I didn't noticed anything weird after removing it. Tested on Vertex, but should be happening on Vertex Dark and Vertex Light too.

With 1px line:
![screenshot_2017-07-27_14-21-24](https://user-images.githubusercontent.com/9440816/28683621-9f4a1960-72d7-11e7-9c27-e745dfe6b002.png)

Without 1px line:
![screenshot_2017-07-27_14-22-38](https://user-images.githubusercontent.com/9440816/28683631-ab9b48c4-72d7-11e7-8caa-883531797bfd.png)

Code to remove it:
```css
#navigator-toolbox:after {
  display: none !important;
}
```

**Comment by oberon-manjaro** [comment]
It looks like you are using some other custom theming in your browser that changes the pages' original css. For me youtube does not have a dark background ... it looks like this:

![screenshot_2017-07-27_21-10-54](https://user-images.githubusercontent.com/11800714/28687842-20b94e84-7310-11e7-97b9-b425900c2028.png)


and here's facebook's blue at the top of the page - no bright line here for me either:

![screenshot_2017-07-27_21-08-54](https://user-images.githubusercontent.com/11800714/28687815-fe3d62d2-730f-11e7-8559-d827668b9d72.png)

**Comment by hertz1** [comment]
I'm not using any custom theme, that's the new Youtube layout. You need activate it first in [here](https://www.youtube.com/new). Then click on you profile picture and activate the dark theme from the menu.

I'm using Firefox Developer Edition 55, though. Didn't tested on 54 stable.

**Comment by oberon-manjaro** [comment]
So is this issue only with YouTube's dark theme or do you have another example where you see that line?

**Comment by hertz1** [comment]
It happens with others sites too, including manjaro's home page. Tested on 54 stable with a fresh profile and I get the same result. It doesn't happen only with Vertex-Maia-Light userChrome.css.

![screenshot_2017-07-27_18-01-57](https://user-images.githubusercontent.com/9440816/28692254-35aa74cc-72f6-11e7-81ad-d1675d820831.png)

**Comment by oberon-manjaro** [comment]
I don't know. I cannot reproduce this:

![hp](https://user-images.githubusercontent.com/11800714/28710804-bd6d1cc2-7385-11e7-8572-46616e484b5f.png)

**Comment by hertz1** [comment]
What happens if you add the following code to your userChrome.css?

```css
#navigator-toolbox:after {
  display: none !important;
}
```

If you don't notice anything weird, why don't apply this rule by default? It'll fix for those who have the issue and for those who don't, they won't even notice the change.

**Comment by oberon-manjaro** [comment]
Before adding a "bugfix" it is normal procedure to confirm we actually have a reproducible bug that exists not only on one individual system.
In this case it looks to me that something in your other config is causing that line. I have at least four installations on two computers here without the issue and sofar I haven't heard of other instance of this problem.

**Comment by oberon-manjaro** [comment]
Btw when you look at my screenshot of the Facebook header you will see that there isn't just no line but there is a shadow under the address box, while in your YouTube screenshot it is missing!

**Comment by oberon-manjaro** [comment]
When you look closely you can confirm that in all our screenshots.
I think in your case there isn't an extra line but the bottom shadow in your case had the wrong color for whatever reason.
Are you sure you are still using an original untouched css file?

**Comment by hertz1** [comment]
Yes, I made a symbolic link from `/usr/share/themes/Firefox/Vertex-Maia/chrome` to my profile folder, so it's using the default css. I'm not home at the moment, but I'll try to investigate this further.
